# Generated by Django 5.1.1 on 2024-09-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemModel',
            new_name='Items',
        ),
    ]
